#!/bin/bash
# emit-opencode.sh — Emit OpenCode plugin from abstract hook config
#
# Usage:
#   emit-opencode.sh <abstract-hooks.json> [--output <path>] [--dry-run]
#
# Strategy: Generate a TypeScript plugin file that reads .claude/settings.json
# at runtime. This leverages OpenCode's Claude-compatibility bridge — the plugin
# translates Claude Code hook format to OpenCode's event system.
#
# Alternative: Direct opencode.json hooks section (less proven).
#
# Requires: jq, bash 4+

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../scripts/emit-common.sh"

PLATFORM="opencode"
OUTPUT_PATH=".opencode/plugins/cc-hooks.ts"
DRY_RUN=false

usage() {
  echo "Usage: $0 <abstract-hooks.json> [--output <path>] [--dry-run]"
  echo ""
  echo "Emit OpenCode TypeScript plugin from abstract hook config."
  echo ""
  echo "Options:"
  echo "  --output <path>  Output file path (default: .opencode/plugins/cc-hooks.ts)"
  echo "  --dry-run        Print output to stdout instead of writing file"
  echo "  --help           Show this help"
  exit "${1:-0}"
}

# Parse arguments
INPUT_FILE=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --output) OUTPUT_PATH="$2"; shift 2 ;;
    --dry-run) DRY_RUN=true; shift ;;
    --help) usage 0 ;;
    -*) echo "Unknown option: $1" >&2; usage 1 ;;
    *)
      if [[ -z "$INPUT_FILE" ]]; then
        INPUT_FILE="$1"
      else
        echo "Unexpected argument: $1" >&2; usage 1
      fi
      shift
      ;;
  esac
done

if [[ -z "$INPUT_FILE" ]]; then
  echo "ERROR: No input file specified" >&2
  usage 1
fi

require_jq

# Validate input
validation=$(validate_abstract "$INPUT_FILE")
if [[ "$validation" != "OK" ]]; then
  echo "$validation" >&2
  exit 1
fi

# Check for prompt hooks (NOT supported)
if [[ "$(has_prompt_hooks "$INPUT_FILE")" == "true" ]]; then
  warn_prompt_hooks "$PLATFORM"
fi

# Report unsupported events
for event in $(jq -r '.hooks | keys[]' "$INPUT_FILE"); do
  case "$event" in
    SessionStart|SessionEnd|PreToolUse|PostToolUse|Stop) ;;
    *) warn_event "$event" "$PLATFORM" ;;
  esac
done

# Generate OpenCode TypeScript plugin
# This plugin reads .claude/settings.json and maps Claude events to OpenCode events
OUTPUT='// Auto-generated by cc-hooks emit-opencode.sh
// Do not edit manually — regenerate with: emit-hooks.sh --platform opencode
//
// This plugin reads .claude/settings.json and executes hooks at matching
// OpenCode lifecycle events. Requires opencode-hooks-plugin or native
// OpenCode plugin support.

import { spawn } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

interface HookCommand {
  type: "command";
  command: string;
  timeout?: number;
}

interface HookGroup {
  matcher?: string;
  hooks: HookCommand[];
}

interface ClaudeSettings {
  hooks?: Record<string, HookGroup[]>;
}

const SETTINGS_PATH = path.join(".claude", "settings.json");

function loadSettings(): ClaudeSettings | null {
  if (!existsSync(SETTINGS_PATH)) return null;
  try {
    return JSON.parse(readFileSync(SETTINGS_PATH, "utf8"));
  } catch {
    return null;
  }
}

function matcherMatches(matcher: string | undefined, value: string): boolean {
  if (!matcher || matcher === "" || matcher === "*") return true;
  try {
    return new RegExp(`^(?:${matcher})$`).test(value);
  } catch {
    return matcher.split("|").some(t => t.trim().toLowerCase() === value.toLowerCase());
  }
}

function executeHook(command: string, timeout: number = 600_000): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolve) => {
    const proc = spawn("bash", ["-lc", command], {
      timeout,
      env: { ...process.env },
    });
    let stdout = "";
    let stderr = "";
    proc.stdout.on("data", (d) => (stdout += d));
    proc.stderr.on("data", (d) => (stderr += d));
    proc.on("close", (code) => resolve({ code: code ?? 1, stdout, stderr }));
  });
}

export default function ccHooksPlugin() {
  const settings = loadSettings();
  if (!settings?.hooks) return {};

  const hooks = settings.hooks;

  return {
    // Map: Claude SessionStart → OpenCode session.start
    "session.start": async () => {
      for (const group of hooks.SessionStart ?? []) {
        for (const hook of group.hooks ?? []) {
          if (hook.type === "command" && hook.command) {
            await executeHook(hook.command, (hook.timeout ?? 600) * 1000);
          }
        }
      }
    },

    // Map: Claude SessionEnd → OpenCode session.end
    "session.end": async () => {
      for (const group of hooks.SessionEnd ?? []) {
        for (const hook of group.hooks ?? []) {
          if (hook.type === "command" && hook.command) {
            await executeHook(hook.command, (hook.timeout ?? 600) * 1000);
          }
        }
      }
    },

    // Map: Claude PreToolUse → OpenCode tool.execute.before
    "tool.execute.before": async (event: { toolName: string; input: unknown }) => {
      for (const group of hooks.PreToolUse ?? []) {
        if (!matcherMatches(group.matcher, event.toolName)) continue;
        for (const hook of group.hooks ?? []) {
          if (hook.type === "command" && hook.command) {
            const result = await executeHook(hook.command, (hook.timeout ?? 600) * 1000);
            if (result.code === 2) {
              throw new Error(`Hook blocked: ${result.stderr || "blocked by hook"}`);
            }
          }
        }
      }
    },

    // Map: Claude PostToolUse → OpenCode tool.execute.after
    "tool.execute.after": async (event: { toolName: string; input: unknown; result: unknown }) => {
      for (const group of hooks.PostToolUse ?? []) {
        if (!matcherMatches(group.matcher, event.toolName)) continue;
        for (const hook of group.hooks ?? []) {
          if (hook.type === "command" && hook.command) {
            await executeHook(hook.command, (hook.timeout ?? 600) * 1000);
          }
        }
      }
    },

    // Map: Claude Stop → OpenCode session.idle
    "session.idle": async () => {
      for (const group of hooks.Stop ?? []) {
        for (const hook of group.hooks ?? []) {
          if (hook.type === "command" && hook.command) {
            await executeHook(hook.command, (hook.timeout ?? 600) * 1000);
          }
        }
      }
    },
  };
}
'

if [[ "$DRY_RUN" == "true" ]]; then
  echo "$OUTPUT"
  exit 0
fi

# Write to file
OUTPUT_DIR=$(dirname "$OUTPUT_PATH")
mkdir -p "$OUTPUT_DIR"
echo "$OUTPUT" > "$OUTPUT_PATH"

echo "OpenCode plugin emitted to $OUTPUT_PATH" >&2
echo "NOTE: This plugin reads .claude/settings.json. Run emit-claude-code.sh first to generate it." >&2
