"""Type stubs for pytest."""
from typing import Any, Callable, Union, Type

def fixture(
    func: Union[Callable[..., Any], None] = None,
    *,
    scope: str = "function",
    params: Any = None,
    autouse: bool = False,
    ids: Any = None,
    name: Union[str, None] = None,
) -> Any: ...

def raises(
    expected_exception: Union[Type[Exception], tuple[Type[Exception], ...]],
    match: Union[str, None] = None,
) -> Any: ...

class _MarkDecorator:
    pass

mark: _MarkDecorator

class _Param:
    pass

param: _Param

class FixtureRequest: ...
class Metafunc: ...
class Parser: ...
class Config: ...
class Node: ...
class Collector: ...
class Item: ...
class Module: ...
class Class: ...
class Function: ...
class File: ...
