"""
Shared pytest fixtures for technical-content-creation skill tests.

This module provides common fixtures used across all test modules,
including temporary directories, mock configurations, and test data.
"""

import importlib.util
import json
import sys
import pytest
from pathlib import Path
from unittest.mock import MagicMock, patch
from datetime import datetime

# Add scripts directory to Python path for imports
_scripts_dir = Path(__file__).parent.parent / "scripts"
_scripts_dir_abs = _scripts_dir.resolve()
if str(_scripts_dir_abs) not in sys.path:
    sys.path.insert(0, str(_scripts_dir_abs))

# Explicitly register the script modules so they can be imported
# Map importable module names (with underscores) to actual file names (with dashes)
_script_modules = {
    'context_validator': 'context-validator',
    'outline_generator': 'outline-generator',
    'repo_config': 'repo-config',
    'topic_init': 'topic-init',
}

for _module_name, _file_name in _script_modules.items():
    _module_file = _scripts_dir_abs / f"{_file_name}.py"
    if _module_file.exists():
        try:
            spec = importlib.util.spec_from_file_location(_module_name, _module_file)
            if spec and spec.loader:
                module = importlib.util.module_from_spec(spec)
                if _module_name not in sys.modules:
                    sys.modules[_module_name] = module
                    # Execute the module to populate its namespace
                    spec.loader.exec_module(module)
        except Exception as e:
            print(f"Warning: Could not pre-register module {_module_name}: {e}")


# ============================================================================
# Config Directory Fixtures
# ============================================================================

@pytest.fixture
def mock_config_dir(tmp_path):
    """
    Create a temporary config directory for testing.

    Returns:
        Path: Temporary config directory (~/.claude/wt/)
    """
    config_dir = tmp_path / ".claude" / "wt"
    config_dir.mkdir(parents=True)
    return config_dir


@pytest.fixture
def mock_jsonc_file(mock_config_dir):
    """
    Create a sample JSONC file with comments.

    Returns:
        Path: Path to the JSONC config file
    """
    config_file = mock_config_dir / "config.jsonc"
    config_content = """// wt Plugin Configuration
// Auto-generated by technical-content-creation skill
// Last updated: 2026-01-30T00:00:00Z

{
  "version": "1.0.0",
  "last_updated": "2026-01-30T00:00:00Z",
  "technical-content-creation": {
    "tcc_repo_root": "/mock/repo/root",
    "default_collection": "test-collection",
    "auto_create_collections": true,
    "collections_path": "collections"
  }
}
"""
    config_file.write_text(config_content)
    return config_file


@pytest.fixture
def mock_empty_jsonc_file(mock_config_dir):
    """
    Create an empty JSONC file.

    Returns:
        Path: Path to the empty JSONC config file
    """
    config_file = mock_config_dir / "config.jsonc"
    config_file.write_text("{}")
    return config_file


# ============================================================================
# Repository Root Fixtures
# ============================================================================

@pytest.fixture
def mock_repo_root(tmp_path):
    """
    Create a mock TCC repository root with required structure.

    Returns:
        Path: Mock repository root directory
    """
    repo_root = tmp_path / "repo"
    repo_root.mkdir()

    # Create collections.json
    collections_data = {
        "collections": [
            {
                "id": "test-collection",
                "name": "Test Collection",
                "description": "A test collection",
                "path": "collections/test-collection",
                "topic_count": 1,
                "published_count": 0,
                "created_at": "2026-01-30",
                "updated_at": "2026-01-30",
                "tags": ["test"]
            }
        ],
        "last_updated": "2026-01-30T00:00:00Z"
    }
    (repo_root / "collections.json").write_text(
        json.dumps(collections_data, indent=2)
    )

    # Create collections directory and test-collection subdirectory
    collections_dir = repo_root / "collections"
    collections_dir.mkdir()
    (collections_dir / "test-collection").mkdir()

    return repo_root


@pytest.fixture
def mock_valid_repo(mock_repo_root):
    """
    Alias for mock_repo_root for compatibility with test files.

    Returns:
        Path: Mock repository root directory
    """
    return mock_repo_root


@pytest.fixture
def mock_repo_root_without_collections(tmp_path):
    """
    Create a mock repository root without collections directory (invalid).

    Returns:
        Path: Mock repository root directory (invalid structure)
    """
    repo_root = tmp_path / "invalid_repo"
    repo_root.mkdir()
    # Missing collections.json and collections/ directory
    return repo_root


# ============================================================================
# Topic Directory Fixtures
# ============================================================================

@pytest.fixture
def mock_topic_dir(mock_repo_root):
    """
    Create a mock topic directory with all 7 stage folders.

    Returns:
        Path: Mock topic directory with complete structure
    """
    collection_dir = mock_repo_root / "collections" / "test-collection"
    collection_dir.mkdir(exist_ok=True)
    topic_dir = collection_dir / "test-topic"
    topic_dir.mkdir()

    # Create topic.md with frontmatter
    topic_md_content = """---
name: test-topic
title: Test Topic
description: A test topic for unit testing
collection: test-collection
created_at: 2026-01-30
updated_at: 2026-01-30
status: draft
author:
  name: Test Author
  email: test@example.com
tags:
  - test
keywords:
  - test-keyword
stage: 2
version: 1.0.0
review:
  last_reviewed_at: null
  reviewer: null
  status: pending
  feedback: []
links:
  materials: 0-materials/materials-extracted.md
  research: 1-research/research-brief.md
  outline: 2-outline/outline-approved.md
  draft: 3-draft/draft-article.md
  illustration: 4-illustration/
  adaptation: 5-adaptation/
  publish: 6-publish/article.md
stats:
  word_count: null
  reading_time: null
  source_count: 0
  image_count: 0
---

## Additional Notes

This is a test topic.

## Stage Progression

Track progress through stages.
"""
    (topic_dir / "topic.md").write_text(topic_md_content)

    # Create 7 stage folders
    stage_folders = [
        "0-materials",
        "1-research",
        "2-outline",
        "3-draft",
        "4-illustration",
        "5-adaptation",
        "6-publish"
    ]

    # Create subfolders map
    stage_subfolders = {
        "3-draft": ["draft-revisions"],
        "4-illustration": ["images"],
        "6-publish": ["published", "assets"],
        "2-outline": ["materials"]
    }

    for stage in stage_folders:
        stage_dir = topic_dir / stage
        stage_dir.mkdir(exist_ok=True)

        # Create subfolders if defined
        if stage in stage_subfolders:
            for subfolder in stage_subfolders[stage]:
                (stage_dir / subfolder).mkdir(exist_ok=True)

        # Add key files for stages 0-2 (make them complete)
        if stage == "0-materials":
            (stage_dir / "materials.json").write_text('{"materials": []}')
            (stage_dir / "materials-extracted.md").write_text("# Materials Extracted\n\nTest content.")
        elif stage == "1-research":
            (stage_dir / "sources.json").write_text('{"sources": []}')
            (stage_dir / "research-brief.md").write_text("# Research Brief\n\nTest research content.")
        elif stage == "2-outline":
            (stage_dir / "outline-approved.md").write_text("# Outline\n\nTest outline.")

    return topic_dir


@pytest.fixture
def mock_incomplete_topic_dir(mock_repo_root):
    """
    Create a mock topic directory with incomplete stages.

    Returns:
        Path: Mock topic directory with incomplete stages
    """
    collection_dir = mock_repo_root / "collections" / "test-collection"
    collection_dir.mkdir(exist_ok=True)
    topic_dir = collection_dir / "incomplete-topic"
    topic_dir.mkdir()

    # Create topic.md
    (topic_dir / "topic.md").write_text(
        "---\nname: incomplete-topic\nstage: 0\n---\n\n# Incomplete Topic"
    )

    # Create only stage 0 (materials) - incomplete
    materials_dir = topic_dir / "0-materials"
    materials_dir.mkdir()
    (materials_dir / "materials.json").write_text('{}')

    # Other stages don't exist

    return topic_dir


# ============================================================================
# Research Brief Fixture
# ============================================================================

@pytest.fixture
def mock_research_brief(tmp_path):
    """
    Create a mock research brief file with frontmatter.

    Returns:
        Path: Mock research brief file
    """
    research_dir = tmp_path / "1-research"
    research_dir.mkdir()
    brief_file = research_dir / "research-brief.md"
    brief_content = """---
title: Test Topic for Outlines
source_materials: 0-materials/materials-extracted.md
research_type: comprehensive
sources_count: 5
---

# Test Topic for Outlines

## Key Theme 1
Content for theme 1 - important concepts.

## Key Theme 2
Content for theme 2 - practical applications.

## Key Theme 3
Content for theme 3 - advanced considerations.

## Conclusion
Summary of research findings.
"""
    brief_file.write_text(brief_content)
    return brief_file


# ============================================================================
# Outline Directory Fixture
# ============================================================================

@pytest.fixture
def mock_outline_dir(tmp_path):
    """
    Create a mock outline directory.

    Returns:
        Path: Mock outline directory
    """
    outline_dir = tmp_path / "2-outline"
    outline_dir.mkdir()
    return outline_dir


# ============================================================================
# CLI Arguments Fixtures
# ============================================================================

@pytest.fixture
def mock_cmd_validate_args():
    """Create mock CLI arguments for cmd_validate."""
    return MagicMock(validate=True)


@pytest.fixture
def mock_cmd_status_args():
    """Create mock CLI arguments for cmd_status."""
    return MagicMock(status=True)


@pytest.fixture
def mock_cmd_detect_stage_args():
    """Create mock CLI arguments for cmd_detect_stage."""
    args = MagicMock()
    args.detect_stage = True
    args.json = False
    return args


@pytest.fixture
def mock_cmd_verify_dependencies_args():
    """Create mock CLI arguments for cmd_verify_dependencies."""
    args = MagicMock()
    args.verify_dependencies = True
    args.stage = None
    return args


@pytest.fixture
def mock_cmd_init_args():
    """Create mock CLI arguments for cmd_init."""
    args = MagicMock()
    args.topic = "test-topic"
    args.collection = "test-collection"
    args.title = "Test Topic"
    args.description = "A test topic"
    args.author = "Test Author"
    args.email = "test@example.com"
    args.tag = "test"
    args.notes = "Test notes"
    return args


@pytest.fixture
def mock_cmd_generate_args():
    """Create mock CLI arguments for cmd_generate."""
    args = MagicMock()
    args.options = 3
    args.length = "long"
    args.interactive = False
    args.confidence = "MEDIUM"
    return args


@pytest.fixture
def mock_cmd_approve_args():
    """Create mock CLI arguments for cmd_approve."""
    args = MagicMock()
    args.approve = "b"
    args.approved_by = "user"
    return args


# ============================================================================
# Collections Data Fixtures
# ============================================================================

@pytest.fixture
def mock_collections_data():
    """
    Create mock collections.json data.

    Returns:
        dict: Mock collections data
    """
    return {
        "collections": [
            {
                "id": "test-collection",
                "name": "Test Collection",
                "description": "A test collection",
                "path": "collections/test-collection",
                "topic_count": 2,
                "published_count": 0,
                "created_at": "2026-01-30",
                "updated_at": "2026-01-30",
                "tags": ["test"]
            },
            {
                "id": "another-collection",
                "name": "Another Collection",
                "description": "Another test collection",
                "path": "collections/another-collection",
                "topic_count": 0,
                "published_count": 0,
                "created_at": "2026-01-30",
                "updated_at": "2026-01-30",
                "tags": []
            }
        ],
        "last_updated": "2026-01-30T00:00:00Z"
    }


# ============================================================================
# Topic Data Fixture
# ============================================================================

@pytest.fixture
def mock_topic_data():
    """
    Create mock topic metadata.

    Returns:
        dict: Mock topic data
    """
    return {
        "title": "Test Topic",
        "description": "A test topic for unit testing",
        "author_name": "Test Author",
        "author_email": "test@example.com",
        "primary_tag": "test",
        "primary_keyword": "test-keyword",
        "notes": "Test notes for unit testing"
    }


# ============================================================================
# Sys Path Fixture for Module Imports
# ============================================================================

@pytest.fixture(autouse=True)
def add_scripts_to_sys_path(monkeypatch, tmp_path):
    """
    Automatically add scripts directory to sys.path for all tests.

    This allows tests to import from the scripts module directly.
    """
    import sys
    scripts_dir = Path(__file__).parent.parent / "scripts"
    if str(scripts_dir) not in sys.path:
        monkeypatch.syspath_prepend(str(scripts_dir))


# ============================================================================
# TCC Config Fixture
# ============================================================================

@pytest.fixture
def mock_tcc_config():
    """
    Create mock TCC configuration.

    Returns:
        dict: Mock TCC config
    """
    return {
        "tcc_repo_root": "/mock/repo/root",
        "default_collection": "test-collection",
        "auto_create_collections": True,
        "collections_path": "collections"
    }
